from dataclasses import dataclass

SEABORN_PLOTS = {
    "Scatter Plot": {
        "Image": "sample_graphs/scatter_plot.png",
        "x-axis_data_type": ["float"],
        "y-axis_data_type": ["float"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "hue",
            "style",
            "size",
            "palette",
            "alpha",
            "marker",
            "s",
            "edgecolor",
        ],
    },
    "Line Plot": {
        "Image": "sample_graphs/line_plot.png",
        "x-axis_data_type": ["float", "int"],
        "y-axis_data_type": ["float", "int"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "hue",
            "style",
            "size",
            "palette",
            "alpha",
            "linewidth",
            "marker",
            "linestyle",
        ],
    },
    "Regression Plot": {
        "Image": "sample_graphs/regression_plot.png",
        "x-axis_data_type": ["float"],
        "y-axis_data_type": ["float"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "color",
            "marker",
            "scatter",
            "fit_reg",
            "ci",
            "line_kws",
            "scatter_kws",
            "truncate",
        ],
    },
    "Bar Plot": {
        "Image": "sample_graphs/bar_plot.png",
        "x-axis_data_type": ["object", "category"],
        "y-axis_data_type": ["float", "int"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "hue",
            "palette",
            "errorbar",
            "ci",
            "capsize",
            "orient",
            "estimator",
            "width",
        ],
    },
    "Count Plot": {
        "Image": "sample_graphs/count_plot.png",
        "x-axis_data_type": ["object", "category"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "hue",
            "palette",
            "orient",
            "order",
            "hue_order",
            "dodge",
            "width",
            "saturation",
        ],
    },
    "Box Plot": {
        "Image": "sample_graphs/box_plot.png",
        "x-axis_data_type": ["object", "category"],
        "y-axis_data_type": ["float", "int"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "hue",
            "palette",
            "orient",
            "order",
            "hue_order",
            "width",
            "fliersize",
            "linewidth",
        ],
    },
    "Violin Plot": {
        "Image": "sample_graphs/violin_plot.png",
        "x-axis_data_type": ["object", "category"],
        "y-axis_data_type": ["float", "int"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "hue",
            "palette",
            "orient",
            "order",
            "hue_order",
            "bw",
            "inner",
            "linewidth",
        ],
    },
    "Swarm Plot": {
        "Image": "sample_graphs/swarm_plot.png",
        "x-axis_data_type": ["object", "category"],
        "y-axis_data_type": ["float", "int"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "hue",
            "palette",
            "size",
            "dodge",
            "orient",
            "marker",
            "alpha",
            "linewidth",
        ],
    },
    "Strip Plot": {
        "Image": "sample_graphs/strip_plot.png",
        "x-axis_data_type": ["object", "category"],
        "y-axis_data_type": ["float", "int"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "hue",
            "palette",
            "size",
            "jitter",
            "dodge",
            "orient",
            "alpha",
            "linewidth",
        ],
    },
    "Histogram": {
        "Image": "sample_graphs/histogram.png",
        "x-axis_data_type": ["float", "int"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "bins",
            "binwidth",
            "stat",
            "kde",
            "hue",
            "multiple",
            "element",
            "palette",
        ],
    },
    "KDE Plot": {
        "Image": "sample_graphs/kde_plot.png",
        "x-axis_data_type": ["float"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "fill",
            "bw_adjust",
            "cut",
            "clip",
            "hue",
            "multiple",
            "palette",
            "alpha",
        ],
    },
    "ECDF Plot": {
        "Image": "sample_graphs/ecdf_plot.png",
        "x-axis_data_type": ["float", "int"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "hue",
            "stat",
            "complementary",
            "palette",
            "alpha",
            "marker",
            "linewidth",
            "orientation",
        ],
    },
    "Rug Plot": {
        "Image": "sample_graphs/rug_plot.png",
        "x-axis_data_type": ["float", "int"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "hue",
            "height",
            "expand_margins",
            "palette",
            "alpha",
            "linewidth",
            "orientation",
            "ax",
        ],
    },
    "Heatmap": {
        "Image": "sample_graphs/heatmap.png",
        "x-axis_data_type": ["float", "int"],
        "y-axis_data_type": ["float", "int"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "annot",
            "fmt",
            "cmap",
            "center",
            "vmin",
            "vmax",
            "linewidths",
            "linecolor",
        ],
    },
    "Pair Plot": {
        "Image": "sample_graphs/pair_plot.png",
        "x-axis_data_type": ["float", "int"],
        "y-axis_data_type": ["float", "int"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "hue",
            "palette",
            "kind",
            "diag_kind",
            "markers",
            "corner",
            "plot_kws",
            "diag_kws",
        ],
    },
    "Joint Plot": {
        "Image": "sample_graphs/joint_plot.png",
        "x-axis_data_type": ["float", "int"],
        "y-axis_data_type": ["float", "int"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "hue",
            "kind",
            "palette",
            "height",
            "ratio",
            "marginal_ticks",
            "space",
            "joint_kws",
        ],
    },
    "Cluster Map": {
        "Image": "sample_graphs/cluster_map.png",
        "x-axis_data_type": ["object", "category"],
        "y-axis_data_type": ["object", "category"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "cmap",
            "center",
            "annot",
            "linewidths",
            "figsize",
            "row_cluster",
            "col_cluster",
            "standard_scale",
            "z_score",
            "dendrogram_ratio",
        ],
    },
    "Relational Plot": {
        "Image": "sample_graphs/relational_plot.png",
        "x-axis_data_type": ["float", "int"],
        "y-axis_data_type": ["float", "int"],
        "parameters": [
            "x-axis",
            "y-axis",
            "axis title",
            "title",
            "legend",
            "grid",
            "hue",
            "style",
            "size",
            "palette",
            "alpha",
            "marker",
            "kind",
            "col",
        ],
    },
}

@dataclass
class PlotSpec:
    graph_name: str
    image: str
    x_axis_data_type: list[str]
    y_axis_data_type: list[str]
    parameters: list[str]

def get_plot_spec(graph_name: str) -> PlotSpec:
    return PlotSpec(
        graph_name=graph_name,
        image=f"sample_graphs/{graph_name.lower().replace(' ', '_')}.png",
        x_axis_data_type=SEABORN_PLOTS[graph_name]["x-axis_data_type"],
        y_axis_data_type=SEABORN_PLOTS[graph_name]["y-axis_data_type"],
        parameters=SEABORN_PLOTS[graph_name]["parameters"],
    )
